import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
			>
				{children}
				<footer>
          <p
          className="text-sm underline hover:text-[#550000] transition-colors duration-200 absolute right-5 bottom-5">
						<Link
							href={"/privacy-policy"}
						>
							Privacy|Terms
						</Link>
					</p>
				</footer>
			</body>
		</html>
  );
}
