import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import db from "./database/db";

// Graceful shutdown of database
process.on("SIGINT", async () => {
	await db.close();
	process.exit(0);
});

const montserrat = Montserrat({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.className} antialiased min-w-dvh min-h-dvh font-sans`}
			>
				<>{children}</>
				<footer>
					<p className="fixed text-sm underline hover:text-[#550000] transition-colors duration-200 absolute right-5 bottom-5 overflow-hidden">
						<Link href={"/privacy-policy"}>Privacy|Terms</Link>
					</p>
				</footer>
			</body>
		</html>
	);
}
